### ISSUE TITLE
1.2.18 crashes in icmp functions due to reversed strcpy() calls

### ISSUE THREAD

**Issue by eriksejr** [Cacti/spine#211] opened 2021-07-07 02:19 UTC
```
Starting program: /tmp/cacti-spine-1.2.18/spine -C /usr/local/spine/etc/spine.conf --poller 1 --first 0 --last 1091 --mibs
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
SPINE: Using spine config file [/usr/local/spine/etc/spine.conf]
Version 1.2.18 starting
[Detaching after vfork from child process 139037]
[Detaching after vfork from child process 139038]
[Detaching after vfork from child process 139039]
[Detaching after vfork from child process 139040]
[New Thread 0x7ffff6ea5700 (LWP 139041)]
[New Thread 0x7ffff66a4700 (LWP 139042)]
[New Thread 0x7ffff5ea3700 (LWP 139043)]
[New Thread 0x7ffff56a2700 (LWP 139044)]
[New Thread 0x7ffff4ea1700 (LWP 139045)]
[New Thread 0x7fffe7fff700 (LWP 139046)]
[New Thread 0x7fffe77fe700 (LWP 139047)]
[Thread 0x7ffff6ea5700 (LWP 139041) exited]
2021/07/06 16:43:00 - SPINE: Poller[1] PID[139033] WARNING: Unknown error while resolving host ▒4 (Name or service not known)
free(): invalid pointer
[New Thread 0x7ffff6ea5700 (LWP 139048)]

Thread 3 "spine" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff66a4700 (LWP 139042)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) thread apply all bt

Thread 9 (Thread 0x7ffff6ea5700 (LWP 139048)):
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:78
#1  0x00007ffff7c83530 in ?? () at allocatestack.c:311 from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ffff6ea5700 in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 8 (Thread 0x7fffe77fe700 (LWP 139047)):
#0  0x00007ffff7ba012b in __GI___select (nfds=80, readfds=0x7fffe77d7870, writefds=0x0, exceptfds=0x0, timeout=0x7fffe77d7830) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00007ffff7e5ab91 in snmp_sess_synch_response () from /lib/x86_64-linux-gnu/libnetsnmp.so.35
#2  0x0000555555562a34 in snmp_get (current_host=0x7fffdc0013b0, snmp_oid=0x7fffdc0032f0 ".1.3.6.1.2.1.1.3.0") at snmp.c:367
#3  0x000055555556feec in ping_snmp (host=0x7fffdc0013b0, ping=0x7fffdc002330) at ping.c:193
#4  0x000055555556fc67 in ping_host (host=0x7fffdc0013b0, ping=0x7fffdc002330) at ping.c:94
#5  0x00005555555662d6 in poll_host (host_id=72, host_thread=2, last_host_thread=4, host_data_ids=27, host_time=0x7fffe77fdbd0 "1625604180", host_errors=0x7fffe77fdb00, host_time_double=1625604180.640414) at poller.c:615
#6  0x0000555555564a52 in child (arg=0x5555558608e0) at poller.c:103
#7  0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fffe7fff700 (LWP 139046)):
#0  0x00007ffff7ba012b in __GI___select (nfds=79, readfds=0x7fffe7fd8870, writefds=0x0, exceptfds=0x0, timeout=0x7fffe7fd8830) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00007ffff7e5ab91 in snmp_sess_synch_response () from /lib/x86_64-linux-gnu/libnetsnmp.so.35
#2  0x0000555555562a34 in snmp_get (current_host=0x7ffff0001aa0, snmp_oid=0x7ffff0003cd0 ".1.3.6.1.2.1.1.3.0") at snmp.c:367
#3  0x000055555556feec in ping_snmp (host=0x7ffff0001aa0, ping=0x7ffff0002a20) at ping.c:193
#4  0x000055555556fc67 in ping_host (host=0x7ffff0001aa0, ping=0x7ffff0002a20) at ping.c:94
#5  0x00005555555662d6 in poll_host (host_id=72, host_thread=1, last_host_thread=4, host_data_ids=27, host_time=0x7fffe7ffebd0 "1625604180", host_errors=0x7fffe7ffeb00, host_time_double=1625604180.640414) at poller.c:615
#6  0x0000555555564a52 in child (arg=0x555555860760) at poller.c:103
#7  0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7ffff4ea1700 (LWP 139045)):
#0  __lll_lock_wait (futex=futex@entry=0x555555581360 <seteuid_lock>, private=0) at lowlevellock.c:52
#1  0x00007ffff7c860a3 in __GI___pthread_mutex_lock (mutex=0x555555581360 <seteuid_lock>) at ../nptl/pthread_mutex_lock.c:80
#2  0x000055555556456a in thread_mutex_lock (mutex=2) at locks.c:224
#3  0x00005555555702bd in ping_icmp (host=0x7fffd80013b0, ping=0x7fffd8002330) at ping.c:298
#4  0x000055555556faf3 in ping_host (host=0x7fffd80013b0, ping=0x7fffd8002330) at ping.c:70
#5  0x00005555555662d6 in poll_host (host_id=741, host_thread=4, last_host_thread=4, host_data_ids=44, host_time=0x7ffff4ea0bd0 "1625604180", host_errors=0x7ffff4ea0b00, host_time_double=1625604180.6357591) at poller.c:615
#6  0x0000555555564a52 in child (arg=0x5555558605c0) at poller.c:103
#7  0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7ffff56a2700 (LWP 139044)):
#0  __lll_lock_wait (futex=futex@entry=0x555555581360 <seteuid_lock>, private=0) at lowlevellock.c:52
#1  0x00007ffff7c860a3 in __GI___pthread_mutex_lock (mutex=0x555555581360 <seteuid_lock>) at ../nptl/pthread_mutex_lock.c:80
#2  0x000055555556456a in thread_mutex_lock (mutex=2) at locks.c:224
#3  0x00005555555702bd in ping_icmp (host=0x7fffe00013b0, ping=0x7fffe0002330) at ping.c:298
#4  0x000055555556faf3 in ping_host (host=0x7fffe00013b0, ping=0x7fffe0002330) at ping.c:70
#5  0x00005555555662d6 in poll_host (host_id=741, host_thread=3, last_host_thread=4, host_data_ids=44, host_time=0x7ffff56a1bd0 "1625604180", host_errors=0x7ffff56a1b00, host_time_double=1625604180.6357591) at poller.c:615
#6  0x0000555555564a52 in child (arg=0x555555860440) at poller.c:103
#7  0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ffff5ea3700 (LWP 139043)):
#0  futex_wait (private=0, expected=4294967294, futex_word=0x7ffff6ea5d1c) at ../sysdeps/nptl/futex-internal.h:141
#1  futex_wait_simple (private=0, expected=4294967294, futex_word=0x7ffff6ea5d1c) at ../sysdeps/nptl/futex-internal.h:172
#2  setxid_mark_thread (t=t@entry=0x7ffff6ea5700, cmdp=0x7ffff5e7d050) at allocatestack.c:975
#3  0x00007ffff7c82c05 in __nptl_setxid (cmdp=0x7ffff5e7d050) at allocatestack.c:1091
#4  0x00007ffff7b9fc89 in __GI_seteuid (uid=<optimized out>) at ../sysdeps/unix/sysv/linux/seteuid.c:34
#5  __GI_seteuid (uid=<optimized out>) at ../sysdeps/unix/sysv/linux/seteuid.c:24
#6  0x00005555555703fa in ping_icmp (host=0x7fffec0013b0, ping=0x7fffec002330) at ping.c:333
#7  0x000055555556faf3 in ping_host (host=0x7fffec0013b0, ping=0x7fffec002330) at ping.c:70
#8  0x00005555555662d6 in poll_host (host_id=741, host_thread=2, last_host_thread=4, host_data_ids=44, host_time=0x7ffff5ea2bd0 "1625604180", host_errors=0x7ffff5ea2b00, host_time_double=1625604180.6357591) at poller.c:615
#9  0x0000555555564a52 in child (arg=0x555555850d80) at poller.c:103
--Type <RET> for more, q to quit, c to continue without paging--  c
#10 0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ffff66a4700 (LWP 139042)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7aad859 in __GI_abort () at abort.c:79
#2  0x00007ffff7b183ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7c42285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7b2047c in malloc_printerr (str=str@entry=0x7ffff7c404ae "free(): invalid pointer") at malloc.c:5347
#4  0x00007ffff7b21cac in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x00007ffff7b91cb0 in __GI_freeaddrinfo (ai=0x0) at ../sysdeps/posix/getaddrinfo.c:2521
#6  0x0000555555572267 in init_sockaddr (name=0x7ffff667e140, hostname=0x7fffe80034b0 "\200\064", port=7) at ping.c:980
#7  0x000055555557062a in ping_icmp (host=0x7fffe80013b0, ping=0x7fffe8002330) at ping.c:377
#8  0x000055555556faf3 in ping_host (host=0x7fffe80013b0, ping=0x7fffe8002330) at ping.c:70
#9  0x00005555555662d6 in poll_host (host_id=741, host_thread=1, last_host_thread=4, host_data_ids=44, host_time=0x7ffff66a3bd0 "1625604180", host_errors=0x7ffff66a3b00, host_time_double=1625604180.6357591) at poller.c:615
#10 0x0000555555564a52 in child (arg=0x555555850d40) at poller.c:103
#11 0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#12 0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff71c1940 (LWP 139033)):
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:78
#1  0x00007ffff7c822ec in create_thread (pd=pd@entry=0x7ffff6ea5700, attr=attr@entry=0x7ffffff03a30, stopped_start=stopped_start@entry=0x7ffffff0386e, stackaddr=stackaddr@entry=0x7ffff6ea4dc0, thread_ran=thread_ran@entry=0x7ffffff0386f) at ../sysdeps/unix/sysv/linux/createthread.c:101
#2  0x00007ffff7c83e10 in __pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=<optimized out>) at pthread_create.c:817
#3  0x000055555555c7c9 in main (argc=10, argv=0x7fffffffe5d8) at spine.c:824
```

**Comment by netniV** [comment] 2021-09-02 20:41
This is a duplicate of several other posts so I'm going to close this.

**Closed by netniV** 2021-09-02 20:41 UTC
