### ISSUE TITLE
spine 1.2.18 segfault

### ISSUE THREAD

**Issue by jdcoats** [Cacti/spine#217] opened 2021-07-08 21:27 UTC
```
2021/07/08 17:25:02 - SPINE: Poller[Main Poller] PID[15020] WARNING: Unknown error while resolving host  (Name or service not known)
2021/07/08 17:25:01 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2021/07/08 17:25:01 - POLLER: Poller[Main Poller] PID[15014] WARNING: There are 2 processes detected as overrunning a polling cycle, please investigate
```

**Comment by jdcoats** [comment] 2021-07-08 21:29
```
# spine -R -V 5
SPINE: Using spine config file [/etc/spine.conf]
WARNING: DB_PreG is no longer supported
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The path_php_server variable is /var/www/localhost/htdocs/cacti/script_server.php
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The path_cactilog variable is /var/www/localhost/htdocs/cacti/log/cacti.log
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The log_destination variable is 1 (FILE)
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The path_php variable is /usr/bin/php
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The availability_method variable is 1
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The ping_recovery_count variable is 3
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The ping_failure_count variable is 2
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The ping_method variable is 1
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The ping_retries variable is 1
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The ping_timeout variable is 400
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The snmp_retries variable is 3
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The log_perror variable is 1
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The log_pwarn variable is 1
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The boost_redirect variable is 1
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The boost_rrd_update_enable variable is 1
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The log_pstats variable is 0
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The threads variable is 40
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The polling interval is 60 seconds
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The number of concurrent processes is 1
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The script timeout is 5
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The selective_device_debug variable is
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The spine_log_level variable is 0
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The number of php script servers to run is 10
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: StartDevice='-1', EndDevice='-1', TotalPHPScripts='1'
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The PHP Script Server is Required
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: The Maximum SNMP OID Get Size is 10
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 1
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection Pool of 40 threads.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 0.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 2
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 1.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 3
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 2.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 4
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 3.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 5
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 4.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 6
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 5.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 7
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 6.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 8
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 7.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 9
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 8.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 10
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 9.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 11
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 10.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 12
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 11.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 13
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 12.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 14
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 13.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 15
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 14.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 16
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 15.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 17
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 16.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 18
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 17.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 19
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 18.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 20
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 19.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 21
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 20.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 22
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 21.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 23
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 22.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 24
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 23.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 25
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 24.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 26
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 25.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 27
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 26.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 28
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 27.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 29
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 28.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 30
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 29.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 31
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 30.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 32
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 31.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 33
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 32.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 34
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 33.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 35
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 34.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 36
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 35.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 37
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 36.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 38
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 37.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 39
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 38.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 40
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Creating Local Connection 39.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Total Connections made 41
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Version 1.2.18 starting
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: MySQL is Thread Safe!
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Spine running as 0 UID, 0 EUID
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Spine is running as root.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Spine has got ICMP
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Initializing Net-SNMP API
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: Initializing PHP Script Server(s)
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[0] PHP Script Server Routine Starting
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[0] PHP Script Server About to FORK Child Process
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[0] PHP Script Server Child FORK Success
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[0] Confirmed PHP Script Server running using readfd[47], writefd[46]
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[1] PHP Script Server Routine Starting
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[1] PHP Script Server About to FORK Child Process
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[1] PHP Script Server Child FORK Success
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[1] Confirmed PHP Script Server running using readfd[49], writefd[48]
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[2] PHP Script Server Routine Starting
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[2] PHP Script Server About to FORK Child Process
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[2] PHP Script Server Child FORK Success
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[2] Confirmed PHP Script Server running using readfd[51], writefd[50]
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[3] PHP Script Server Routine Starting
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[3] PHP Script Server About to FORK Child Process
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[3] PHP Script Server Child FORK Success
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[3] Confirmed PHP Script Server running using readfd[53], writefd[52]
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[4] PHP Script Server Routine Starting
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[4] PHP Script Server About to FORK Child Process
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[4] PHP Script Server Child FORK Success
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[4] Confirmed PHP Script Server running using readfd[55], writefd[54]
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[5] PHP Script Server Routine Starting
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[5] PHP Script Server About to FORK Child Process
2021/07/08 17:28:40 - SPINE: Poller[1] PID[15247] DEBUG: SS[5] PHP Script Server Child FORK Success
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[5] Confirmed PHP Script Server running using readfd[57], writefd[56]
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[6] PHP Script Server Routine Starting
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[6] PHP Script Server About to FORK Child Process
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[6] PHP Script Server Child FORK Success
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[6] Confirmed PHP Script Server running using readfd[59], writefd[58]
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[7] PHP Script Server Routine Starting
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[7] PHP Script Server About to FORK Child Process
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[7] PHP Script Server Child FORK Success
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[7] Confirmed PHP Script Server running using readfd[61], writefd[60]
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[8] PHP Script Server Routine Starting
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[8] PHP Script Server About to FORK Child Process
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[8] PHP Script Server Child FORK Success
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[8] Confirmed PHP Script Server running using readfd[63], writefd[62]
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[9] PHP Script Server Routine Starting
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[9] PHP Script Server About to FORK Child Process
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[9] PHP Script Server Child FORK Success
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: SS[9] Confirmed PHP Script Server running using readfd[65], writefd[64]
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] Spine will support multithread device polling.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Initial Value of Available Threads is 40 (0 outstanding)
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Valid Thread to be Created
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Available Threads is 39 (1 outstanding)
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: In Poller, About to Start Polling of Device for Device ID 0
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Valid Thread to be Created
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Available Threads is 38 (2 outstanding)
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Traversing Local Connection Pool for free connection.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 0.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Allocating Local Pool ID 0.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: In Poller, About to Start Polling of Device for Device ID 571
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Traversing Local Connection Pool for free connection.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 0.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 1.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Allocating Local Pool ID 1.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Valid Thread to be Created
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Available Threads is 37 (3 outstanding)
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] get_namebyhost(10.9.76.85) - Allocating name_t
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: In Poller, About to Start Polling of Device for Device ID 2122
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] get_namebyhost(10.9.76.85) - Token #1
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] get_hostbyname(10.9.76.85) - No matching method for 10 chars: 10.9.76.85
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] get_namebyhost(10.9.76.85) - Setting hostname: 10.9.76.85
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Traversing Local Connection Pool for free connection.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] Device[571] INFO: SNMP Device '10.9.76.85' has timeout 4000000 (4000), retries 3
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 0.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 1.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 2.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Allocating Local Pool ID 2.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Valid Thread to be Created
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] Device[571] IPv4 address 10.9.76.85 (10.9.76.85)
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Available Threads is 36 (4 outstanding)
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] Device[571] DEBUG: Entering ICMP Ping
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: In Poller, About to Start Polling of Device for Device ID 665
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Traversing Local Connection Pool for free connection.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 0.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 1.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 2.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 3.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] WARNING: Unknown error while resolving host ▒v▒L (Name or service not known)
FATAL: Spine Encountered a Segmentation Fault
Generating backtrace...0 line(s)...
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Allocating Local Pool ID 3.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] Device[0] HT[1] NOTE: There are '2' Polling Items for this Device
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Valid Thread to be Created
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: In Poller, About to Start Polling of Device for Device ID 678
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] get_namebyhost(summary) - Allocating name_t
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Available Threads is 35 (5 outstanding)
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Traversing Local Connection Pool for free connection.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] get_namebyhost(summary) - Token #1
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 0.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] DEBUG: Checking Local Pool ID 1.
2021/07/08 17:28:41 - SPINE: Poller[1] PID[15247] get_hostbyname(summary) - No matching method for 7 chars: summary
```

**Comment by jdcoats** [comment] 2021-07-08 21:41
It was this commit that broke it for me
https://github.com/Cacti/spine/commit/9c6e198295d86d6ac0f66d1222da0081ee55cbbf
I didn't report it at that time because of your notes stating "This is partially implemented"
I assumed that it would have been noticed and resolved before 1.2.18 release. Sorry for not bringing it up a month ago.

**Comment by jdcoats** [comment] 2021-07-08 21:56
@TheWitness @netniV consider pulling 1.2.18 spine release. We had to revert to 1.2.17 spine

**Comment by eriksejr** [comment] 2021-07-08 23:19
This is a duplicate of #211 and #209. The patch in the pull request should take care of it.

**Comment by netniV** [comment] 2021-07-09 07:26
Yes, this is a duplicate and we are aware of the issue, thanks @jdcoats

**Closed by netniV** 2021-07-09 07:26 UTC
