### ISSUE TITLE
spine hangs in infinite loop during debug device check

### ISSUE THREAD

**Issue by reberse** [Cacti/spine#17] opened 2017-03-28 16:16 UTC
If there are debug devices defined, and is_debug_device() is called when the device ID passed to it is not the first one in the debug_devices array, it will go into an infinite loop.  This will manifest as spine timing out when polling (right after the child thread is spawned) and eating up 100% of a cpu.

The issue can be fixed by changing line 224 in util.c as follows:

From:
       while(i < 100) {

To:
       while(i++ < 100) {

**Comment by cigamit** [comment] 2017-03-28 23:39
Duplicate of Issue #16

**Closed by cigamit** 2017-03-28 23:39 UTC
Labels: duplicate
