### ISSUE TITLE
Failed host lookup causes spine to crash

### ISSUE THREAD

**Issue by ahouston** [Cacti/spine#155] opened 2020-04-22 15:08 UTC
**Describe the bug**

When the hostname field of cacti.host is not set to an IP address, and the host resolution fails, spine will crash with the following:
```
# /usr/local/spine/bin/spine -C /etc/cacti/spine.conf --poller 1
SPINE: Using spine config file [/etc/cacti/spine.conf]
SPINE: Version 1.2.11 starting
2020/04/22 16:52:16 - SPINE: Poller[1] PID[26484] WARNING: Unable to determine address info for test.blah.com (Name or service not known)
munmap_chunk(): invalid pointer
2020/04/22 16:52:16 - SPINE: Poller[1] PID[26484] FATAL: Spine Encountered An Unhandled Exception Signal Number: '6' [110, Connection timed out] (Spine thread)
```

**GDB Backtrace**

```
2020/04/22 17:03:03 - SPINE: Poller[1] PID[30657] SPINE: Active Threads is 8, Pending is 8
2020/04/22 17:03:03 - SPINE: Poller[1] PID[30657] WARNING: Unable to determine address info for test.blah.com (Name or service not known)
munmap_chunk(): invalid pointer

Thread 36 "spine" received signal SIGABRT, Aborted.
[Switching to Thread 0x7f49a8eb9700 (LWP 30761)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f49add10801 in __GI_abort () at abort.c:79
#2  0x00007f49add59897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f49ade86b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f49add6090a in malloc_printerr (str=str@entry=0x7f49ade887a8 "munmap_chunk(): invalid pointer") at malloc.c:5350
#4  0x00007f49add67ecc in munmap_chunk (p=0x7f49add5fef0 <__GI__IO_list_resetlock+16>) at malloc.c:2846
#5  __GI___libc_free (mem=0x7f49add5ff00 <__GI__IO_str_underflow>) at malloc.c:3117
#6  0x00007f49addd889d in __GI_freeaddrinfo (ai=0x7f49add5e3c0 <__GI__IO_default_uflow>) at ../sysdeps/posix/getaddrinfo.c:2569
#7  0x000055e9d05c467a in get_address_type (host=host@entry=0x7f49980122b0) at ping.c:872
#8  0x000055e9d05c6058 in ping_host (host=host@entry=0x7f49980122b0, ping=ping@entry=0x7f4998013230) at ping.c:68
#9  0x000055e9d05c0aef in poll_host (host_id=host_id@entry=1609, host_thread=host_thread@entry=1, last_host_thread=last_host_thread@entry=1, host_data_ids=host_data_ids@entry=0, 
    host_time=host_time@entry=0x7f49a8eb8db0 "2020-04-22 17:03:03", host_errors=host_errors@entry=0x7f49a8eb8da8, host_time_double=host_time_double@entry=1587567783.0734) at poller.c:571
#10 0x000055e9d05c2ea6 in child (arg=<optimized out>) at poller.c:77
#11 0x00007f49ae0c86db in start_thread (arg=0x7f49a8eb9700) at pthread_create.c:463
#12 0x00007f49addf188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - Spine: SPINE 1.2.11

**Comment by TheWitness** [comment] 2020-04-25 18:02
It almost looks like you have a broken DNS.  I tried to reproduce this with a bad hostname and could not.

**Comment by TheWitness** [comment] 2020-04-25 18:09
Okay, this is fixed now.

**Closed** 2020-05-03 20:03 UTC
Labels: bug, resolved
